### ISSUE TITLE
关于使用的疑惑

### ISSUE THREAD

**Issue by alexk1028** [4paradigm/k8s-device-plugin#10]
### 1. Issue or feature description
我们正准备尝试这个gpu插件，假如我的集群里只有一块GPU，假如我分割成两块，根据"分配到节点上任务所需要的vGPU数量，不能大于节点实际GPU数量"这条限制，我实际上能启动/可用的算力实例（使用gpu的应用）是否也只有一个

**Comment by archlitchi** [comment]
不是，你可以启动2个算力实例。我这个限制的意思是你不能切割成2块之后跑个双卡任务

**Comment by alexk1028** [comment]
> 不是，你可以启动2个算力实例。在你的场景下，这个限制的意思是不能跑单机双卡任务，如果你的机器上有4张物理GPU的话，那么你单个算力实例最多可以同时使用4张卡

你这样解释我明白了，非常感谢！！
