### ISSUE TITLE
启用vGPU之后pod内执行nvidia-smi报错Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by tbbrave** [4paradigm/k8s-device-plugin#11]
大佬，K8S小白请教个问题，还请麻烦指导一下

### 1. Issue or feature description
启用vGPU之后pod内执行nvidia-smi报错Segmentation fault (core dumped)

### 2. Steps to reproduce the issue
master节点8核16G腾讯云虚拟机，node节点20核80G腾讯云虚拟机带一张nvidia T4显卡。操作系统为ubuntu server 18.04
node节点安装如下安装docker、nvidia-docker2并开启vgpu，使用的镜像是latest，参数均为默认（尝试过修改参数但是结果一样）
![image](https://user-images.githubusercontent.com/9070847/142757435-ca48b94f-180e-4d30-bec7-5e78a600e456.png)

执行如下操作
![image](https://user-images.githubusercontent.com/9070847/142757467-d334c92e-7bb2-4d1e-8b72-2f35bbf3a84b.png)
进入pod内部执行nvidia-smi结果如下
![image](https://user-images.githubusercontent.com/9070847/142757474-adcbe295-b79d-453a-8bfa-42676ab73c8c.png)

在带显卡的宿主机上执行nvidia-smi是没有问题的
docker版本20.10
K8S版本1.19.0使用kubeadm安装，kubelet版本也是1.19.0
docker info结果如下，daemon.json也已经配置了runtime和default-runtime为nvidia
![image](https://user-images.githubusercontent.com/9070847/142757592-d4d549c3-a44f-4a91-b80d-5a337085d29e.png)

**Comment by archlitchi** [comment]
可以在容器内执行env看一下吗

**Comment by tbbrave** [comment]
> 

我今天重试了一下，当我的集群内GPU超过一张卡的时候，vgpu是可以生效的，运行任务也是没问题的，但是只有一张卡的时候会出现上面的错误，也可能是参数设置的问题？我等下班之后如果复现出来了把env贴出来看下。感谢大佬了

**Comment by archlitchi** [comment]
好的，后续上slack上交流吧，更方便一些
