### ISSUE TITLE
can use for 2080Ti/1080Ti ？

### ISSUE THREAD

**Issue by sunhao12121** [4paradigm/k8s-device-plugin#13]
感谢您的工作
本人新手，请问是否支持2080Ti/1080Ti等其他非tesla V100环境？

**Comment by sunhao12121** [comment]
还有个问题请教一下，device-split-count可以设置节点有多少个pod，想请问有参数可以设置每个pod大小吗，例如一个pod 1/4 一个pod 1/4 一个pod 1/2，每个大小自定义

**Comment by archlitchi** [comment]
第一个问题，可以的
第二个不行，每个pod申请的GPU都是一样大的，如果想按照显存大小申请的话，需要使用我们的调度器https://github.com/4paradigm/k8s-vgpu-scheduler
