### ISSUE TITLE
分配2张vgpu却只能看到1张

### ISSUE THREAD

**Issue by xwhuang0923** [4paradigm/k8s-device-plugin#17]
一台8张A100 的机器，每张卡分成5张vgpu --device-split-count=5。创建一个2 vgpu的pod，在容器里使用nvidia-smi 命令只能看到一张vgpu，/dev 目录下能看到两个gpu。k8s-vgpu-plugin 为v0.9.0.18

**Comment by archlitchi** [comment]
能不能把容器里面env的结果发一下？

**Comment by archlitchi** [comment]
要不先升级到0.9.0.19试一下，如果还是不work的话，加我wx：xuanzong4493

**Comment by archlitchi** [comment]
@xwhuang0923 怎么样，升级之后能work吗

**Comment by xwhuang0923** [comment]
@archlitchi 你好，我发现是 NVIDIA_DEVICE_MAP 这个环境设置的问题。容器启动时对环境变量有修改，所以导致NVIDIA_DEVICE_MAP中第二个vgpu的环境变量设置没成功。
